version: "3.7"
volumes:
  node_modules_frontend: {}
  node_modules_backend: {}
services:

  common-frontend:
    build: ./nginx
    ports:
      - "3000:3000"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.10
  #https-portal:
   # image: steveltn/https-portal:1.13
    #ports:  # Syntax: 'HOST:CONTAINER'
    #  - '80:80'
    #  - '443:443'
    #volumes:
    #  - ./volumes/ssl_certs:/var/lib/https-portal
    #links:  # Syntax: service:hostname
    #  - factor
    #restart: unless-stopped
    #environment: 
    #  STAGE: local
    #  DOMAINS: 'www.fsmpi.uni-bayreuth.de => fsmpi.uni-bayreuth.de, fsmpi.uni-bayreuth.de -> http://factor:3000'
    #networks:
    #  homepage-network:
    #    ipv4_address: 172.23.2.10

  #mongodb:
   # image: mongo:4.2.3
   # restart: unless-stopped
   # ports:
   #   - "27017:27017"
   # volumes:
   #   - mongo_data:/data/db
   #   - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js
   # environment:
   #   - MONGO_INITDB_ROOT_USERNAME=root
   #   - MONGO_INITDB_ROOT_PASSWORD=mongodbROOT
   #   - MONGO_INITDB_DATABASE=factor
   # networks:
   #   homepage-network:
   #     ipv4_address: 172.23.2.30
  keystone:
    build: ./backend
    image: keystone:0.9.9
    working_dir: "/var/keystone"
    volumes:
      - .:/var/keystone
      - node_modules_backend:/var/node_modules
    ports:
      - "4000"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.40

  vuecms:
    build: ./frontend
    image: vuecms:0.9.9
    working_dir: "/var/vuecms"
    volumes:
      - .:/var/vuecms
      - node_modules_frontend:/var/node_modules
    ports:
      - "5000"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.50

networks:
  homepage-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.2.0/24
