version: "3.7"
volumes:
  node_modules_frontend: {}
  node_modules_backend: {}
services:

  common-frontend:
    environment:
      - BUCKET=bucket
      - BUCKET_BASE_URL=localhost
      - BUCKET_PORT=9000
    env_file:
      - shared.env
    build: ./nginx 
      #context: ./nginx
      #dockerfile: ./nginx/Dockerfile
      #volumes:
      #- ./strapi-backend/config:/opt/app/config
      #- ./strapi-backend/src:/opt/app/src
      #- ./strapi-backend/package.json:/opt/package.json
      #- ./strapi-backend/package-lock.json:/opt/package-lock.json
      #- ./strapi-backend/.env:/opt/app/.env
    ports:
      - "80:80"
      - "443:443"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.10

  strapi:
    environment:
      - HOST=strapi
      - PORT=1337
      - URL_SERVER=https://www.fsmpi.uni-bayreuth.de/v1
      - S3_REGION=de
      - S3_BUCKET=bucket
      - S3_ENDPOINT=http://www.fsmpi.uni-bayreuth.de
      - URL_ADMIN=http://backend.fsmpi.lan/admin
    env_file:
      - shared.env
      - strapi.env
    build: ./strapi-backend
    image: strapi:1.0.0
    #working_dir: "/opt"
    #stdin_open: true
    #tty: true
    volumes:
      - ./strapi-backend/config:/opt/app/config
      - ./strapi-backend/src:/opt/app/src
      - ./strapi-backend/package.json:/opt/package.json
      - ./strapi-backend/package-lock.json:/opt/package-lock.json
      - ./strapi-backend/.env:/opt/app/.env
    ports:
      - "1337:1337"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.40

  vuecms:
    build: ./frontend
    image: vuecms:1.0.0
    working_dir: "/var/vuecms"
    volumes:
      - ./frontend:/var/vuecms
      - /var/vuecms/dist-ssr
      - node_modules_frontend:/var/vuecms/node_modules
    ports:
      - "5000"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.50

networks:
  homepage-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.2.0/24
  #https-portal:
   # image: steveltn/https-portal:1.13
    #ports:  # Syntax: 'HOST:CONTAINER'
    #  - '80:80'
    #  - '443:443'
    #volumes:
    #  - ./volumes/ssl_certs:/var/lib/https-portal
    #links:  # Syntax: service:hostname
    #  - factor
    #restart: unless-stopped
    #environment: 
    #  STAGE: local
    #  DOMAINS: 'www.fsmpi.uni-bayreuth.de => fsmpi.uni-bayreuth.de, fsmpi.uni-bayreuth.de -> http://factor:3000'
    #networks:
    #  homepage-network:
    #    ipv4_address: 172.23.2.10

  #mongodb:
   # image: mongo:4.2.3
   # restart: unless-stopped
   # ports:
   #   - "27017:27017"
   # volumes:
   #   - mongo_data:/data/db
   #   - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js
   # environment:
   #   - MONGO_INITDB_ROOT_USERNAME=root
   #   - MONGO_INITDB_ROOT_PASSWORD=mongodbROOT
   #   - MONGO_INITDB_DATABASE=factor
   # networks:
   #   homepage-network:
   #     ipv4_address: 172.23.2.30
