version: "3.7"
volumes:
  node_modules_frontend: {}
  strapi_uploads:
    external: true
services:

  common-frontend:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "8000:8000"
      #- "443:443"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.10

  strapi:
    restart: always
    environment:
      - HOST=strapi
      - PORT=1337
      - URL_ADMIN=http://web.fsmpi:8000/admin
      - URL_SERVER=https://fsmpi.uni-bayreuth.de/v1
    env_file:
      - shared.env
    build: ./strapi-backend
    image: strapi:1.0.0
    #working_dir: "/opt"
    #stdin_open: true
    #tty: true
    volumes:
      - strapi_uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.40

  vuecms:
    restart: always
    env_file:
      - shared.env
    build: ./frontend
    image: vuecms:1.0.0
    working_dir: "/var/vuecms"
    volumes:
      - ./frontend:/var/vuecms
      - /var/vuecms/dist-ssr
      - /var/vuecms/production
      - node_modules_frontend:/var/vuecms/node_modules
    ports:
      - "5000"
    networks:
      homepage-network:
        ipv4_address: 172.23.2.50

networks:
  homepage-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.2.0/24
  #https-portal:
   # image: steveltn/https-portal:1.13
    #ports:  # Syntax: 'HOST:CONTAINER'
    #  - '80:80'
    #  - '443:443'
    #volumes:
    #  - ./volumes/ssl_certs:/var/lib/https-portal
    #links:  # Syntax: service:hostname
    #  - factor
    #restart: unless-stopped
    #environment: 
    #  STAGE: local
    #  DOMAINS: 'www.fsmpi.uni-bayreuth.de => fsmpi.uni-bayreuth.de, fsmpi.uni-bayreuth.de -> http://factor:3000'
    #networks:
    #  homepage-network:
    #    ipv4_address: 172.23.2.10

  #mongodb:
   # image: mongo:4.2.3
   # restart: unless-stopped
   # ports:
   #   - "27017:27017"
   # volumes:
   #   - mongo_data:/data/db
   #   - ./mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js
   # environment:
   #   - MONGO_INITDB_ROOT_USERNAME=root
   #   - MONGO_INITDB_ROOT_PASSWORD=mongodbROOT
   #   - MONGO_INITDB_DATABASE=factor
   # networks:
   #   homepage-network:
   #     ipv4_address: 172.23.2.30
